version: "3.9"
services:
  api-gate-way:
    image: api-gate-way:v1
    container_name: api-gate-way-v1
    build:
      context: ./api-gate-way
      dockerfile: Dockerfile
    ports:
      - 8765:8765
    depends_on:
      - naming-server
      - rabbitmq
    networks:
      - net01
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit

  naming-server:
    image: naming-server:v1
    build:
      context: ./naming-server
      dockerfile: Dockerfile
    container_name: naming-server-v1
    ports:
      - 8761:8761
    networks:
      - net01

  currency-conversion:
    image: currency-conversion:v1
    build:
      context: ./currency-conversion-service
      dockerfile: Dockerfile
    container_name: currency-conversion-v1
    ports:
      - 8100:8100
    depends_on:
      - naming-server
      - rabbitmq
    networks:
      - net01
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit

  currency-exchange:
    image: currency-exchange:v1
    build:
      context: ./currency-exchange-service
      dockerfile: Dockerfile
    container_name: currency-exchange-v1
    ports:
      - 8000:8000
    depends_on:
      - naming-server
      - db
      - rabbitmq
    networks:
      - net01
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit

  limits-service:
    image: limits-service:v1
    build:
      context: ./limits-service
      dockerfile: Dockerfile
    container_name: limits-service-v1
    ports:
      - 8080:8080
    networks:
      - net01

  db:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5434:5432
    networks:
      - net01

  zipkin-server:
    image: openzipkin/zipkin:2.23
    container_name: zipkin
    ports:
      - 9411:9411
    networks:
      - net01
    environment:
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - net01

networks:
  net01:
    driver: bridge
